Repository datashim-io/datashim, pull requests merged in 2021-09, with the labels that each got.

#127 Introduce Caching PlacementInfo in DatasetInternal Status
  src/dataset-operator/pkg/apis/com/v1alpha1/datasetinternal_types.go
  src/dataset-operator/pkg/apis/com/v1alpha1/zz_generated.deepcopy.go
Labels: enhancement, cache-plugin

#82 Expose the placements of CEPH cache-plugin components in the Status of DatasetInternal
  plugins/ceph-cache-plugin/cmd/manager/main.go
  plugins/ceph-cache-plugin/go.mod
  plugins/ceph-cache-plugin/go.sum
  plugins/ceph-cache-plugin/pkg/controller/dataset/ceph_related_objects.go
  plugins/ceph-cache-plugin/pkg/controller/dataset/dataset_controller.go
  plugins/ceph-cache-plugin/pkg/controller/dataset/dataset_finalizer.go
Labels: enhancement, cache-plugin, ceph

#133 fix: use anonymous credentials with goofys
  src/csi-s3/pkg/s3/mounter_goofys.go
Labels: enhancement
