Repository datashim-io/datashim, pull requests merged in 2022-06, with the labels that each got.

#179 Adding instructions for development workflow
  docs/GolangVSCodeGit.md
  docs/pictures/vscode-gopath.png
  docs/pictures/vscode-ws.png
Labels: documentation, size/M

#177 Update operator-sdk to v1.20 and K8s to v1.22+
  Makefile
  build-tools/Makefile
  build-tools/helpers.mk
  plugins/ceph-cache-plugin/go.mod
  release-tools/manifests/dlf-arm64.yaml
  release-tools/manifests/dlf-ibm-k8s.yaml
  release-tools/manifests/dlf-ibm-oc.yaml
  release-tools/manifests/dlf-ppc64le.yaml
  release-tools/manifests/dlf.yaml
  src/dataset-operator/Dockerfile
  src/dataset-operator/admissioncontroller/mutatingwebhook.go
  src/dataset-operator/api/v1alpha1/dataset_types.go
  src/dataset-operator/api/v1alpha1/datasetinternal_types.go
  src/dataset-operator/api/v1alpha1/groupversion_info.go
  src/dataset-operator/api/v1alpha1/zz_generated.deepcopy.go
  src/dataset-operator/chart/templates/apps/operator.yaml
  src/dataset-operator/chart/templates/crds/com.ie.ibm.hpsys_datasetinternals_crd.yaml
  src/dataset-operator/chart/templates/crds/com.ie.ibm.hpsys_datasets_crd.yaml
  src/dataset-operator/chart/templates/rbac/role.yaml
  src/dataset-operator/cmd/manager/main.go
  src/dataset-operator/controllers/archive_handler.go
  src/dataset-operator/controllers/dataset_controller.go
  src/dataset-operator/controllers/datasetinternal_controller.go
  src/dataset-operator/controllers/metastore_client.go
  src/dataset-operator/controllers/suite_test.go
  src/dataset-operator/go.mod
  src/dataset-operator/go.sum
  src/dataset-operator/hack/boilerplate.go.txt
  src/dataset-operator/main.go
  src/dataset-operator/pkg/admissioncontroller/mutate.go
  src/dataset-operator/pkg/apis/addtoscheme_com_v1alpha1.go
  src/dataset-operator/pkg/apis/apis.go
  src/dataset-operator/pkg/apis/com/group.go
  src/dataset-operator/pkg/apis/com/v1alpha1/doc.go
  src/dataset-operator/pkg/apis/com/v1alpha1/register.go
  src/dataset-operator/pkg/apis/com/v1alpha1/zz_generated.openapi.go
  src/dataset-operator/pkg/controller/add_dataset.go
  src/dataset-operator/pkg/controller/add_datasetinternal.go
  src/dataset-operator/pkg/controller/controller.go
  src/dataset-operator/tools.go
  src/dataset-operator/version/version.go
  src/generate-keys/webhook.yaml.template
Labels: dependencies, size/XXL

#184 switching to quay.io/datashim-io
  build-tools/Makefile
  chart/values.yaml
  release-tools/manifests/dlf-arm64.yaml
  release-tools/manifests/dlf-ibm-k8s.yaml
  release-tools/manifests/dlf-ibm-oc.yaml
  release-tools/manifests/dlf-oc.yaml
  release-tools/manifests/dlf-ppc64le.yaml
  release-tools/manifests/dlf.yaml
  src/dataset-operator/chart/templates/apps/operator.yaml
  src/generate-keys/webhook.yaml.template
Labels: bug, size/M

#186 Update CSI-S3
  src/csi-s3/chart/templates/csi-s3.yaml
  src/csi-s3/chart/templates/driver.yaml
  src/csi-s3/cmd/s3driver/Dockerfile.full
  src/csi-s3/go.mod
  src/csi-s3/go.mod.goofys
  src/csi-s3/go.sum
  src/csi-s3/pkg/s3/config.go
  src/csi-s3/pkg/s3/controllerserver.go
  src/csi-s3/pkg/s3/mounter.go
  src/csi-s3/pkg/s3/mounter_s3backer.go
  src/csi-s3/pkg/s3/mounter_s3fs.go
  src/csi-s3/pkg/s3/nodeserver.go
  src/csi-s3/pkg/s3/s3-client.go
  src/csi-s3/pkg/s3/s3-driver.go
  src/csi-s3/pkg/s3/util.go
Labels: dependencies, size/L
